# Ultra-minimal config.yml for NeMo Guardrails
models:
  - type: main
    engine: ollama
    model: gemma3:4b-it-q4_K_M
    parameters:
      base_url: http://host.docker.internal:11434

# Ensure all expected sections are dictionaries, not lists
instructions: []
user_messages: {}
bot_messages: {}
flows: []
actions: []
prompts: []

# Basic rails - completely empty to avoid any conflicts
rails:
  input:
    flows: []
  output:
    flows: []
