# version: '3.8' # Removed obsolete version tag

services:
  frontend:
    build: ./frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - VITE_API_BASE_URL=http://backend:8000
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - backend # Depends only on backend now
    networks:
      - app-network

  backend:
    build: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    environment:
      # Point to the host machine where Ollama is running
      - OLLAMA_BASE_URL=http://host.docker.internal:11434
      - CHROMA_HOST=chromadb
      - CHROMA_PORT=8000
      - EMBEDDING_MODEL_NAME=all-MiniLM-L6-v2
      - OLLAMA_MODEL=llama3
    depends_on:
      - chromadb # Depends only on chromadb now
    networks:
      - app-network
    # Add extra_hosts if host.docker.internal doesn't work on Linux
    # extra_hosts:
    #   - "host.docker.internal:host-gateway"

  chromadb:
    # Pin ChromaDB to a specific version instead of using latest
    image: chromadb/chroma:0.4.24
    ports:
      - "8001:8000" # Host port 8001 maps to container port 8000
    volumes:
      - chromadb_data:/chroma/chroma
    networks:
      - app-network

volumes:
  chromadb_data:

networks:
  app-network:
    driver: bridge
