# version: '3.8' # Removed obsolete version tag

services:
  frontend:
    build: ./frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - VITE_API_BASE_URL=http://backend:8000
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - backend
    networks:
      - app-network

  backend:
    build: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    environment:
      - OLLAMA_BASE_URL=http://host.docker.internal:11434
      - CHROMA_HOST=chromadb
      - CHROMA_PORT=8000
      - EMBEDDING_MODEL_NAME=all-MiniLM-L6-v2
      - OLLAMA_MODEL=llama3
    depends_on:
      - chromadb
    networks:
      - app-network
    # Add extra_hosts if host.docker.internal doesn't work on Linux
    # extra_hosts:
    #   - "host.docker.internal:host-gateway"

  chromadb:
    # Pin ChromaDB server to version 0.5.5
    image: chromadb/chroma:0.5.20
    ports:
      - "8001:8000" # Host port 8001 maps to container port 8000
    volumes:
      - chromadb_data:/chroma/chroma # Persist ChromaDB data
    networks:
      - app-network
    # ChromaDB 0.5.x server mode should be default.
    # Explicit command can be added if server doesn't start correctly:
    # command: "uvicorn chromadb.app:app --host 0.0.0.0 --port 8000 --workers 1 --reload"
    # Environment variables for server configuration (optional, defaults are usually fine)
    # environment:
    #   - CHROMA_SERVER_HOST=0.0.0.0
    #   - CHROMA_SERVER_HTTP_PORT=8000
    #   - CHROMA_PERSIST_PATH=/chroma/chroma
    #   - ANONYMIZED_TELEMETRY=FALSE # If you want to disable telemetry

volumes:
  chromadb_data:

networks:
  app-network:
    driver: bridge
