# Minimal docker-compose.yml for dependencies only
# Run FastAPI locally with: uvicorn backend.main:app --reload --host 0.0.0.0 --port 8000
# Note: Uses your local Ollama installation instead of containerized version

services:
  # Frontend - only when you need the UI
  frontend:
    build: ./frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - VITE_API_BASE_URL=http://localhost:8000  # Points to local FastAPI
      - CHOKIDAR_USEPOLLING=true
    profiles: ["ui"]  # Optional - only run when needed

  # ChromaDB for vector storage - only when you need RAG
  chromadb:
    image: chromadb/chroma:latest
    ports:
      - "8001:8000"
    volumes:
      - chroma_data:/chroma/chroma
    profiles: ["rag"] 
    environment:
      - CHROMA_SERVER_HOST=0.0.0.0
      - CHROMA_SERVER_PORT=8000
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/v1/heartbeat"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  chroma_data:
