# version: '3.8' # Removed by user, keeping it removed.

services:
  frontend:
    build: ./frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules # Cache node_modules
    environment:
      - VITE_API_BASE_URL=http://backend:8000 # Frontend (in Docker) to Backend (in Docker)
      - CHOKIDAR_USEPOLLING=true # For hot reloading in some environments
    depends_on:
      - backend
    networks:
      - app-network

  backend:
    build: ./backend
    ports:
      - "8000:8000" # Expose backend to host
    volumes:
      - ./backend:/app # Mount backend code
    environment:
      # User's existing environment variables:
      - OLLAMA_BASE_URL=http://host.docker.internal:11434 # For backend to directly access Ollama on host
      - CHROMA_HOST=chromadb
      - CHROMA_PORT=8000 # ChromaDB's internal port
      - EMBEDDING_MODEL_NAME=all-MiniLM-L6-v2
      - OLLAMA_MODEL=llama3
      # Added for NeMo Guardrails:
      - NEMO_GUARDRAILS_SERVER_URL=http://nemo-guardrails:8001 # Backend to Guardrails service
    depends_on:
      - chromadb
      - nemo-guardrails # Ensure guardrails starts before backend
    networks:
      - app-network
    # Add extra_hosts if host.docker.internal doesn't work on your Linux distribution
    # for the backend to reach host Ollama (if it needs to directly).
    # extra_hosts:
    #   - "host.docker.internal:host-gateway"


  nemo-guardrails:
    build: ./nemo_guardrails_build
    volumes:
      - ./guardrails_config:/app/config/guardrails_config 
    command: >-
      nemoguardrails server
        --config /app/config             
        --default-config-id guardrails_config
        --port 8001
    ports:
      - "8002:8001"
    networks: [app-network]


  chromadb:
    image: chromadb/chroma:0.5.20 # User-specified version
    ports:
      - "8001:8000" # Host port 8001 maps to container port 8000
    volumes:
      - chromadb_data:/chroma/chroma # Persist ChromaDB data
    networks:
      - app-network
    # environment:
    #   - ANONYMIZED_TELEMETRY=FALSE

volumes:
  chromadb_data: # Persists ChromaDB data

networks:
  app-network:
    driver: bridge
