# Ultra-minimal NeMo Guardrails config for Banking Assistant
models:
  - type: main
    engine: ollama
    model: gemma3:latest
    parameters:
      base_url: "http://localhost:11434"

instructions:
  - type: general
    content: "You are a professional banking AI assistant specialized in financial services, account management, and banking regulations."

prompts:
  - task: self_check_input
    content: |
      Your task is to check if the user message below complies with the company policy for talking with the company AI assistant.

      Company policy for the AI assistant:
      - Should only discuss banking, financial services, account management, and related topics
      - Should not provide specific financial advice without proper disclaimers
      - Should not discuss non-banking topics like weather, entertainment, or personal matters
      - Should maintain professional banking standards

      User message: "{{ user_input }}"

      Question: Should the above message be blocked (Yes or No)?
      Answer:

  - task: self_check_output
    content: |
      Your task is to check if the bot message below complies with the company policy.

      Company policy for the AI assistant:
      - Should only provide banking and financial information
      - Should include appropriate disclaimers for financial advice
      - Should decline to discuss non-banking topics politely
      - Should maintain professional banking standards

      Bot message: "{{ bot_response }}"

      Question: Should the above message be blocked (Yes or No)?
      Answer:

# Define user intents
rails:
  input:
    flows:
      - self check input

  output:
    flows:
      - self check output